BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TRAVAIL';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SERVICE';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE VOISIN';
EXCEPTION
 WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
	RAISE;
	END IF;
END;
/


CREATE TABLE VOISIN (
     IDVOISIN NUMERIC(2,0),
     NOM VARCHAR(10),
     PRENOM VARCHAR(10),
     VILLE VARCHAR(12),
     RUE VARCHAR(12),
     CODEPOSTAL NUMERIC (6,0),
     CONSTRAINT PK_VOISIN PRIMARY KEY (IDVOISIN));
     
     
CREATE TABLE SERVICE  (
    IDSERVICE NUMERIC (2,0),
    LIBELLE VARCHAR(12),
    CONSTRAINT PK_SERVICE PRIMARY KEY(IDSERVICE));
    
    
CREATE TABLE TRAVAIL (
    IDSERV NUMERIC (2,0),
    IDVOIS NUMERIC (2,0),
    DATESERVICE DATE,
    PRIX NUMERIC (10,0),
    CONSTRAINT PK_TRAVAIL PRIMARY KEY (IDSERV, IDVOIS, DATESERVICE),
    CONSTRAINT FK_SERVICE_TRAVAIL FOREIGN KEY (IDSERV) REFERENCES SERVICE (IDSERVICE) ON DELETE CASCADE,
    CONSTRAINT FK_VOISIN_TRAVAIL FOREIGN KEY (IDVOIS) REFERENCES VOISIN (IDVOISIN) ON DELETE CASCADE
);    
