ALTER session SET NLS_DATE_FORMAT='DD-MM-YYYY' ; 

/* 
Paramètres d'affichage
*/

DROP INDEX IF EXISTS idx_ABO;
DROP VIEW IF EXISTS Livre_auteur;


SET PAGESIZE 30
COLUMN COLUMN_NAME FORMAT A30
SET LINESIZE 300


ALTER TABLE ABONNE ADD(
	DATE_NAI DATE,
	TYPE_AB VARCHAR(10) CHECK (TYPE_AB IN ('ADULTE', 'ENFANT')),
	CAT_AB VARCHAR(15) CHECK (CAT_AB IN ('REGULIER', 'OCCASIONNEL', 'A PROBLEME', 'EXCLU'))
);

ALTER TABLE ABONNE
	MODIFY TARIF NUMERIC(5,0);


CREATE UNIQUE INDEX idx_emp
ON EMPRUNT (NUM_EX, NUM_AB); 

CREATE VIEW Livre_auteur AS
SELECT TITRE, SIECLE, AUTEUR.NOM, AUTEUR.PRENOM
FROM LIVRE, AUTEUR
WHERE LIVRE.NUM_AU = AUTEUR.NUM_AU; 