
package calculator.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMathsWS", targetNamespace = "http://ws.calculator/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMathsWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.calculator/", className = "calculator.client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.calculator/", className = "calculator.client.AddResponse")
    @Action(input = "http://ws.calculator/IMathsWS/addRequest", output = "http://ws.calculator/IMathsWS/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://ws.calculator/", className = "calculator.client.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://ws.calculator/", className = "calculator.client.DivideResponse")
    @Action(input = "http://ws.calculator/IMathsWS/divideRequest", output = "http://ws.calculator/IMathsWS/divideResponse")
    public int divide(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://ws.calculator/", className = "calculator.client.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://ws.calculator/", className = "calculator.client.MultiplyResponse")
    @Action(input = "http://ws.calculator/IMathsWS/multiplyRequest", output = "http://ws.calculator/IMathsWS/multiplyResponse")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "substract", targetNamespace = "http://ws.calculator/", className = "calculator.client.Substract")
    @ResponseWrapper(localName = "substractResponse", targetNamespace = "http://ws.calculator/", className = "calculator.client.SubstractResponse")
    @Action(input = "http://ws.calculator/IMathsWS/substractRequest", output = "http://ws.calculator/IMathsWS/substractResponse")
    public int substract(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
