
package calculator.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MathsWSImplService", targetNamespace = "http://ws.calculator/", wsdlLocation = "http://localhost:8080/maths?wsdl")
public class MathsWSImplService
    extends Service
{

    private final static URL MATHSWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MATHSWSIMPLSERVICE_EXCEPTION;
    private final static QName MATHSWSIMPLSERVICE_QNAME = new QName("http://ws.calculator/", "MathsWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/maths?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATHSWSIMPLSERVICE_WSDL_LOCATION = url;
        MATHSWSIMPLSERVICE_EXCEPTION = e;
    }

    public MathsWSImplService() {
        super(__getWsdlLocation(), MATHSWSIMPLSERVICE_QNAME);
    }

    public MathsWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATHSWSIMPLSERVICE_QNAME, features);
    }

    public MathsWSImplService(URL wsdlLocation) {
        super(wsdlLocation, MATHSWSIMPLSERVICE_QNAME);
    }

    public MathsWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATHSWSIMPLSERVICE_QNAME, features);
    }

    public MathsWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathsWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMathsWS
     */
    @WebEndpoint(name = "MathsWSImplPort")
    public IMathsWS getMathsWSImplPort() {
        return super.getPort(new QName("http://ws.calculator/", "MathsWSImplPort"), IMathsWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMathsWS
     */
    @WebEndpoint(name = "MathsWSImplPort")
    public IMathsWS getMathsWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.calculator/", "MathsWSImplPort"), IMathsWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATHSWSIMPLSERVICE_EXCEPTION!= null) {
            throw MATHSWSIMPLSERVICE_EXCEPTION;
        }
        return MATHSWSIMPLSERVICE_WSDL_LOCATION;
    }

}
